sbatch run_in1.txt.sh
sbatch run_in10.txt.sh
sbatch run_in11.txt.sh
sbatch run_in12.txt.sh
sbatch run_in13.txt.sh
sbatch run_in14.txt.sh
sbatch run_in15.txt.sh
sbatch run_in2.txt.sh
sbatch run_in3.txt.sh
sbatch run_in4.txt.sh
sbatch run_in5.txt.sh
sbatch run_in6.txt.sh
sbatch run_in7.txt.sh
sbatch run_in8.txt.sh
sbatch run_in9.txt.sh
